package com.company;

/*
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

import java.util.ArrayList;

public class Problem2 {

    public static void evenNumbers(int end) {


        long  first = 1;
        long second = 1;
        long fibonacci = 0;
        long total = 0;
        while (fibonacci < end) {

            fibonacci = first + second;

            first = second;

            second = fibonacci;

            if (fibonacci % 2 == 0) {
                total = total + fibonacci;
            }

        }

        System.out.println(total);
    }


}
